play_content:
  target:
    entity:
      integration: musicflow
      domain: media_player
  fields:
    content_type:
      required: true
      example: playlist
      selector:
        select:
          options:
            - song
            - album
            - playlist
            - artist
            - genre
    content_id:
      required: true
      example: "3f1c2b8a-..."
      selector:
        text:
    start_index:
      default: 0
      selector:
        number:
          min: 0
          max: 9999
          mode: box
    play_mode:
      selector:
        select:
          options:
            - order
            - one
            - all
            - shuffle
    enqueue:
      default: false
      selector:
        boolean:

set_play_mode:
  target:
    entity:
      integration: musicflow
      domain: media_player
  fields:
    play_mode:
      required: true
      example: shuffle
      selector:
        select:
          options:
            - order
            - one
            - all
            - shuffle

clear_queue:
  target:
    entity:
      integration: musicflow
      domain: media_player
